
CREATE TABLE IF NOT EXISTS producer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS movie (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    release_year INT NOT NULL,
    title VARCHAR(255) NOT NULL,
    studios VARCHAR(255),
    winner BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS movie_producer (
    movie_id BIGINT NOT NULL,
    producer_id BIGINT NOT NULL,
    PRIMARY KEY (movie_id, producer_id),
    FOREIGN KEY (movie_id) REFERENCES movie(id),
    FOREIGN KEY (producer_id) REFERENCES producer(id)
);

CREATE TABLE IF NOT EXISTS producer_award (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producer_id BIGINT NOT NULL,
    award_year INT NOT NULL,
    FOREIGN KEY (producer_id) REFERENCES producer(id)
);